spring.application.name=tradeservice

spring.datasource.url=jdbc:postgresql://localhost:5432/tradesdb
spring.datasource.username=postgres
spring.datasource.password=root

server.port=8081
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration


# Expose the required Actuator endpoints (Health, Info, Metrics, Prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Always display full health details (e.g., disk space, DB connections) instead of a simple "UP" status
management.endpoint.health.show-details=always

# Attach a common tag to all metrics so you can filter by this application name in Grafana
management.metrics.tags.application=trade-service
