spring.application.name=tradeservice

spring.datasource.url=jdbc:postgresql://etrm-postgres:5432/etrm
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration