CREATE TABLE commodity (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code VARCHAR(255),
                           name VARCHAR(255),
                           price DOUBLE PRECISION
);