-- ============================================
-- Counterparty
-- ============================================

CREATE TABLE counterparty (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              code VARCHAR(50) NOT NULL,
                              name VARCHAR(255) NOT NULL
);


-- ============================================
-- Currency
-- ============================================

CREATE TABLE currency (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          code VARCHAR(10) NOT NULL,
                          name VARCHAR(100) NOT NULL
);


-- ============================================
-- Location
-- ============================================

CREATE TABLE location (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          code VARCHAR(50) NOT NULL,
                          name VARCHAR(255) NOT NULL
);


-- ============================================
-- Idempotency Keys
-- ============================================

CREATE TABLE idempotency_keys (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  idempotency_key VARCHAR(255) NOT NULL,
                                  request_hash VARCHAR(255) NOT NULL,
                                  trade_id BIGINT,

                                  response_body TEXT,

                                  status_code VARCHAR(50) NOT NULL,

                                  created_at TIMESTAMP NOT NULL,

                                  CONSTRAINT uk_idempotency_key
                                      UNIQUE (idempotency_key)
);


-- ============================================
-- Trade
-- ============================================

CREATE TABLE trade (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       trade_type VARCHAR(20) NOT NULL,

                       commodity VARCHAR(100) NOT NULL,

                       quantity NUMERIC(19,6) NOT NULL,

                       price NUMERIC(19,6) NOT NULL,

                       currency VARCHAR(10) NOT NULL,

                       counterparty_id BIGINT,

                       location VARCHAR(100),

                       status VARCHAR(50),

                       version BIGINT,

                       trade_date DATE,

                       updated_at TIMESTAMP,

                       CONSTRAINT fk_trade_counterparty
                           FOREIGN KEY (counterparty_id)
                               REFERENCES counterparty(id)
);

